apiVersion: v1
kind: Secret
metadata:
  name: incident-api-secret
  namespace: sre-lab
  labels:
    app.kubernetes.io/name: incident-api
    app.kubernetes.io/part-of: sre-incident-lab
type: Opaque
stringData:
  LAB_SECRET: "replace-with-local-value"
