apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: incident-api
  namespace: sre-lab
  labels:
    app.kubernetes.io/name: incident-api
    app.kubernetes.io/part-of: sre-incident-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: incident-api

  minReplicas: 1
  maxReplicas: 3

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15

    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
